### ISSUE TITLE
Enhancement - sensor, binary_sensor and input_boolean

### ISSUE THREAD

**Issue by rforro** [hasscontrol/hasscontrol#16]
Have you thought about showing data from sensor/binary_sensor? Looking at the source code the problem with missing sensor action can be easily solved by setting it to null, but showing the value will be needing more work. I think that the ideal place to show its value is where the entity icon is currently drawn, but in this case the function `drawIcon` has to be able write text as well. What do you think?

The second this is controlling state of input_boolean, but this will be easy because it's basically a switch.

**Comment by karlenek** [comment]
Great work, I will try to get som time to checkout and test your pull requests tonight, if not I will do it tomorrow! :)
