### ISSUE TITLE
Local Sensor Data Collection?

### ISSUE THREAD

**Issue by thegamingninja** [hasscontrol/hasscontrol#24]
I'm new to Garmin apps/widgets, so I'm not sure if it's possible, or realistic, but I'm wondering if it would be possible to add the ability to use this widget to send sensor data to Home Assistant, for collecting data locally rather than first sending the data to the Garmin cloud and then integrating with Garmin Connect. 

The perfect example of what I mean is the Home Assistant mobile integration, every once in a while your phone sends sensor data directly to Home Assistant. 

Assuming it's possible, this would be helpful if the API ever goes down or is shut down, and for people who don't like to use cloud integrations.

**Comment by rforro** [comment]
Actually it is not impossible. Garmin apps are able to run on the watch in the background. They even can send data to internet while in background. So to answer your question yes, it is possible, but not with hasscontrol.

**Comment by karlenek** [comment]
I agree with @rforro its possible but unfortenatly out of the scope of this app. I will close the issue since no further action will be required.
