### ISSUE TITLE
Add Venu 2 to compatible devices list

### ISSUE THREAD

**Issue by felixsanz** [hasscontrol/hasscontrol#28]
Hi! Thanks for your work and open sourcing it! Can you please add the new Venu 2 to the compatible devices list? It's almost like Venu 1, so i think it will work fine but i'll report issues if i find them.

**Comment by karlenek** [comment]
I have uploaded a new version to Garmin, it should be available shortly!
Only thing I noticed was that the icons are a little smaller due to the higher resolution on that screen.

Let me know if something is not working as it should, I have no real device to test on!
