### ISSUE TITLE
Unknown error code -400 when refreshing group entities from watch

### ISSUE THREAD

**Issue by ukmgranger** [hasscontrol/hasscontrol#30]
Exactly as title.

I have managed to add a scene okay, but I can't get a group to work.

I'm trying to get this working using a Google Pixel4 with  a Garmin Venu SQ.

Additionally, I'm using  a long lived token.

Any ideas?

**Comment by karlenek** [comment]
What did you write in the group text box?
Did you include the full entity id? like `group.my_group`, or did you just write `my_group`?

**Comment by ukmgranger** [comment]
I have the latter,  so just garmin, not group.garmin

**Comment by karlenek** [comment]
You have to write the full entity id: `group.garmin`.
As stated in the docs: https://github.com/hasscontrol/hasscontrol#group-sync

Please reopen the issue if it still doesn't work.

**Comment by wheindl** [comment]
FYI, I am getting similar errors.  I have the group set up properly in configuration.yaml, and group.garmin in the HassControl settings (set via the Garmin Connect app), using a long lived token.  Long pressing the Back button while HassControl displays on the watch brings up settings including "Refresh entities." Pressing this brings up "Failed Unknown Error Code 400."  Clicking the (unrefreshed) entity in the widget brings up the error "Failed Unknown Error Code 405."
