### ISSUE TITLE
Can't enter port in url on settings page

### ISSUE THREAD

**Issue by RasmusDK** [hasscontrol/hasscontrol#39]
In the settings page for hasscontrol, which I access through the connectIQ, I am not able to add a portnumber to the address of my Home Assistant server. 
If I type an address without a port number I can save the settings, but when I add a port number I get a red box telling me that the value isn't valid. 

I have attached a screenshot of the error. Sorry that it is in Danish, I hope it still makes sense. 
![Screenshot_20211117-080912](https://user-images.githubusercontent.com/17725127/142154181-0168ecf0-8db1-40b7-be94-4bd300bdbe2d.jpg)

**Comment by editicalu** [comment]
I guess this is related to this line from the README:
```
In order to use this widget you need to have an Home Assistant instance accessible over https.
```

**Comment by RasmusDK** [comment]
> I guess this is related to this line from the README:
> 
> ```
> In order to use this widget you need to have an Home Assistant instance accessible over https.
> ```
> 
> If Garmin limits requests to HTTPS, it is possible to block traffic to any non-443 port.

interesting theory. 
I am looking into setting up a reverse proxy and use subdomains. If I get that going then I will avoid the port issue. 

Anyway I saw someone mention this issue on the connectIQ page, and the app author asked to get a bug report on it, so I just wanted to mention that I had the issue as well.

**Comment by karlenek** [comment]
This issue is due to that Garmin has updated their ConnectIQ app and change the behaviour for url validation. I will make some changes to skip Garmins own validation and handle it in the app. 

@RasmusDK, thanks for opening an issue about it, have been away but should be able to push a fix today or tomorrow :)

**Comment by RasmusDK** [comment]
sounds great :)
I tried to look into Garmins api, as my guess was also about the Url type. However besides finding "url" as a possible type for a setting, I couldn't find any documentation about it. So I decided to leave to the expert=you :) 

I was hoping that my reverse proxy could work as a workaround, but I have some issues with loopback on my internal network, and so it won't work when I am at home. The place where I think I will use the app the most. 

Anyway, looking forward to a fix, if one is possible :)
Let me know, if I can test something in regards to it.

**Comment by karlenek** [comment]
@RasmusDK, I have published a new version that should solve the issue :) 
Let me know how it goes!

**Comment by RasmusDK** [comment]
> @RasmusDK, I have published a new version that should solve the issue :) Let me know how it goes!

thank you for the quick work. 
I am able to add the port now, and after figuring out that the "long lived auth code" is very long, and I need to copy it all, it now works :) 
WUHUU :-D
