### ISSUE TITLE
https - untrusted certificates/self signed

### ISSUE THREAD

**Issue by denobula** [hasscontrol/hasscontrol#41]
Since I am at home, when I control my home, I've no "trusted" ssl certificate for the internal URL, 
it is like: https://10.0.0.1:8123 and the certificate does not match the hostname.
Should this work or is there a restriction, where you need a trusted certifcate?

Steps I can reproduce:
1. Start the app on android smartphone
2. enter configuration(URL+1 Scene, **no login token**)
2. Start the app on Garmin watch
**Result**: Login opens, but is just a white page
**Expected**: Login dialogue of HomeAssistant

1. Start the app on android smartphone
2. enter configuration(URL+1 scene and **using long term login token**)
2. Start the app on Garmin watch
3. Select the configured scene 
**Result**: error: -300
**Expected**: scene loading

**Comment by karlenek** [comment]
Unfortunately this is a limitation from Garmin/Android/Apple side and not I'm my control.
Its not possible to use non-valid or self signed certificates :/

The simplest approach would be to access your Home Assistant on a public host address. Your router should take care and route the traffic directly to your home assistant without going through internet, if you are accessing it from your home network and you have normal "home network" setup.
