### ISSUE TITLE
Can't find 'Refresh Entities'

### ISSUE THREAD

**Issue by BGC42** [hasscontrol/hasscontrol#42]
Hi there and thanks for the great app!

One question, everything works fine but after changing the entities in groups.yaml when I go into the settings on my watch I just get 'Push Notifications' and don't get an option to 'Refresh Entities'.  Is something wrong or am I not looking in the right place?

My watch is a Vivoactive 4 and when I start the widget I long-press the bottom right button, get a menu titled 'HassControl', tap on Settings at the top and I get a menu that just has Push Notifications. 

(My phone is running Android 10 if that makes any difference)

-Brendhan

**Comment by karlenek** [comment]
I sounds like you are accessing the wrong menu or something. I will start the app in the simulator for a Vivoactive 4 and see if I can see what you see. But I will have to wait until after the weekend.

**Comment by BGC42** [comment]
Hey karlenek I have discovered what was happening.  I tried filming the issue so you could see it on a physical watch and I noticed a extra menu flicking up briefly for maybe a 1/4sec before settling on the 'Reorder Widget' menu. Once at the 'Reorder Widget' menu if I press the lower right button to go back without going into settings first I get back to the Scenes/Entities menu and from there the settings sub menu does have the elusive Refresh entities option!

Here's a video of what is happening with a slow motion replay so you can see it happening.

https://user-images.githubusercontent.com/96857939/147860676-7ac33bc6-11a4-471e-9964-cc482fcd05ee.mp4

Given the re-order widget menu sounds like a Garmin menu I don't know if you want to fix/workaround this or not. I've got the functionality I need now so it's just a cosmetic issue - at least for me.

Again thanks for the great app/widget and for getting back to me so quickly.  If you ever need any testing on a physical Vivoactive 4 (or a Garmin Edge 520+ or 1030+) I'd be happy to help.

-Brendhan

**Comment by karlenek** [comment]
Hi again,

It seems like the simulator is not behaving the same way as a real watch.
Im not getting that extra menu on top..

I have uploaded a new version 1.5.2 which hopefully should fix the issue, could you test it and verify?
Just please make sure you are testing the correct version, it can take a few hours for Garmin to make it available to download from ConnectIQ store.

/Karl

**Comment by BGC42** [comment]
Hey Karl,, 

Just tested and it's working perfectly now, the 're-order widget' menu is not popping up any more. 👌 

Thanks again and hope you had a great new year.

-Brendhan
