### ISSUE TITLE
Epix 2 compatibility

### ISSUE THREAD

**Issue by mvereecken** [hasscontrol/hasscontrol#46]
I tried to find/install the Connect IQ app, but it says "This app is not compatible with the selected device.".
I suppose there are no real compatibility issues here, but it's a matter of adding the watch to the list of compatible devices?

**Comment by mediacrave** [comment]
Awaiting Fenix 7x compatibility as well

**Comment by Vybo** [comment]
Also would be very thankful for Fenix7(s) compatibility.

**Comment by karlenek** [comment]
Pushed a new version that supports Fenix 7 and Epix 2.
It should be available for download shortly.

**Comment by mvereecken** [comment]
Thank you very much!
